development:
  url: bolt://localhost:7687
  username: <%= ENV['NEO4J_USERNAME'] %>
  password: <%= ENV['NEO4J_PASSWORD'] %>
  encryption: false

test:
  url: bolt://localhost:7688
  username: <%= ENV['NEO4J_USERNAME'] %>
  password: <%= ENV['NEO4J_PASSWORD'] %>
  encryption: false

production:
  url: bolt://localhost:7687
  username: <%= ENV['NEO4J_USERNAME'] %>
  password: <%= ENV['NEO4J_PASSWORD'] %>
  encryption: false