# Demo Student's Survival
def create_demo_game
  #user

  #state
  state = NeoState.create(ch_name: "Sanya", stats: { hp: 100, hunger: 50, money: 100, INT: 0, DEX: 0, STR: 0 }, inventory: {pencil: 1})
  #graph
  graph = NeoGraph.create(title: "demo_graph", text: "demo ghraph of the demo /game/ Student's Survival")

  #nodes
  node0 = NeoNode.create(title: "Start", text: "Старт", kind: :start)
  node1 = NeoNode.create(title: "Choose", text: "Выберите персонажа:", kind: :inbetween)
  node2 =  NeoNode.create(title: "Rich", text: "Саня богат, по каким-то причинам это все, что о нем можно сказать.", kind: :inbetween)
  node3 =  NeoNode.create(title: "Smart", text: "Саня умен, что казалось бы идеально для учебы, но не всегда это так.", kind: :inbetween)
  node4 =  NeoNode.create(title: "Trickster", text: "Ловкость рук и таланты Сани пригодились бы скорее в каком-то другом месте, в другое время, но он сдесь.", kind: :inbetween)
  node5 =  NeoNode.create(title: "Break time", text: "Долгожданный перерыв. В коридорах как всегда в это время суета и шум. Как и любому студенту, Сане хочется есть. Приходится решать эту проблему теми способами, какими он может:", kind: :inbetween)
  node6 =  NeoNode.create(title: "Steal", text: "Без долгих раздумий Саня идет в столовую. Достаточно ловкий и умеющий пользоваться преимуществами неразберихи и толкотни, а также не отягощенный моралью, он достигает своей цели простейшим для него способом: просто под шумок взяв со стола пирожок. В толпе, пока продавец отвлекся, никто не заметил его. ", kind: :inbetween)
  node7 =  NeoNode.create(title: "DoHWForMoney", text: "Саня достаточно легко расправляется с домашними заданиями, и поэтому это приносит ему и небольшой доход. С очередной /соткой/ в кармане, он стал ближе к своей цели ", kind: :inbetween)
  node8 =  NeoNode.create(title: "Stolovaya", text: "Шум в Столовой еще громче, чем в коридорах. Очередь не внушает особых надежд, но выбора не много.", kind: :inbetween)
  node9 =  NeoNode.create(title: "= n19", text: "Choose your character:", kind: :inbetween)
  node10 =  NeoNode.create(title: "WorstEnding", text: "Может способности Сани и не помогают в учебе, зато его скрытность и быстрота позволяют незамеченным никем выбраться из здания. На этом его день в университете закончен.", kind: :finish)
  node11 =  NeoNode.create(title: "PhoneStealthCheck", text: "Лекция обещает быть скучной, поэтому Саня решил занятся чем-то более полезным, по его мнению. Быстро пролистав все соцсети, он запускает какую-то игру, иделаьную для коротания времени. Но вскоре оказывается, что преподавателю отнюдь не все равно, чем заняты студенты.", kind: :inbetween)
  node12 =  NeoNode.create(title: "StillPhone", text: "Как бы то ни было, Саня не намерен обращать слишком много внимания на лекцию и скорее пережидает ее, чем учится", kind: :inbetween)
  node13 =  NeoNode.create(title: "PreEnding", text: "Лекция подходит к концу, как и весь учебный день.", kind: :inbetween)
  node14 =  NeoNode.create(title: "BadEnding", text: "Еще один день подошел к концу. Саня не обдумывает мотивы своих поступков. А хорошие ли решения он принимает -- его это пока что не волнует. А впереди его ждет долгожданный отдых, заслуженный или нет. ", kind: :finish)
  node15 =  NeoNode.create(title: "FineEnding", text: "Не смотря на все сложности, Саня поддерживает баланс между старанием и бездельем, не то, чтобы ему очень этого хотелось, но и кидаться в крайности он не хочет.  ", kind: :finish)
  node16 =  NeoNode.create(title: "GoodEnding", text: "Вцелом прилежный стеден Саня заканчивает тяжелый день в университете. С чувством выполненной работы, он может занятся своими делами, хотя скорее всего посвятит это время учебе.", kind: :finish)
  node17 =  NeoNode.create(title: "StrangeEnding", text: "Удивительно легко дался Сане этот день. за исключением того, что он голоден. Складывается ощущение, будто он уже знает все это наизусть. Впрочем, может быть это и так.", kind: :finish)
  node18 =  NeoNode.create(title: "StudyingHard", text: "Поборов желание отвлечся Саня внимательно пишет конспект. Скорее всего, эти записи еще пригодятся ему.", kind: :inbetween)
  node19 =  NeoNode.create(title: "HW", text: "До этого спокойный Саня вспоминает, что сделать домашнее задание он забыл. Придется до прихода преподавателя найти способ это исправить.", kind: :inbetween)
  node20 =  NeoNode.create(title: "ShowHW", text: "Как бы не решил свою проблему Саня, приходится сдать тетрадь с практикой. Начинается сама лекция. Предмет не самый сложный, но, как часто бывает, скучный и на первый взгляд бесполезный. ", kind: :inbetween)
  node21 =  NeoNode.create(title: "Why is it here?", text: "???", kind: :inbetween)

  #relations
  rel0 = NeoEdge.create(title: "r0", text: "СТАРТ", you_need: "", you_get: "", from_node: node0, to_node: node1 )
  rel1 = NeoEdge.create(title: "r1", text: "Саня не слишком выдающийся студент, но богатый", you_need: "", you_get: "INT+10, DEX+10, STR+10, money+10000", from_node: node1, to_node: node2 )
  rel2 = NeoEdge.create(title: "r2", text: "Саня умен, а это как ничто другое помогает в учебе.", you_need: "", you_get: "INT+21, DEX+16, STR+10, money+100 ", from_node: node1, to_node: node3 )
  rel3 = NeoEdge.create(title: "r3", text: "Таланты Сани это ловкость, наблюдательность и атлетика. Звучит не так полезно, но острый глаз и быстрые пальцы и здесь ему помогали не раз.", you_need: "", you_get: " INT+16, DEX+21, STR+21, money+100 ", from_node: node1, to_node: node4 )
  rel4 = NeoEdge.create(title: "r4", text: "Продолжить", you_need: "", you_get: " not yet implemented ", from_node: node2, to_node: node5 )
  rel5 = NeoEdge.create(title: "r5", text: "Продолжить", you_need: "", you_get: " not yet implemented ", from_node: node3, to_node: node5 )
  rel6 = NeoEdge.create(title: "r6", text: "Продолжить", you_need: "", you_get: " not yet implemented ", from_node: node4, to_node: node5 )
  rel7 = NeoEdge.create(title: "r7", text: "Украсть пирожок", you_need: "DEX>=20", you_get: "hunger-25, hp-50", from_node: node5, to_node: node6 )
  rel8 = NeoEdge.create(title: "r8", text: "Сделать ДЗ за деньги", you_need: "INT>=20", you_get: "money+100", from_node: node5, to_node: node7 )
  rel9 = NeoEdge.create(title: "r9", text: "Сразу пойти в столовую", you_need: "money>=200", you_get: "", from_node: node5, to_node: node8 )
  rel10 = NeoEdge.create(title: "r10", text: "Не есть", you_need: "", you_get: "hunger+25", from_node: node5, to_node: node19 )
  rel11 = NeoEdge.create(title: "r11", text: "Пойти в Столовую", you_need: "", you_get: "hunger-25", from_node: node7, to_node: node8 )
  rel12 = NeoEdge.create(title: "r12", text: "Отправиться в аудиторию", you_need: "", you_get: "", from_node: node6, to_node: node19 )
  rel13 = NeoEdge.create(title: "r13", text: "Отправиться в аудиторию", you_need: "", you_get: "", from_node: node8, to_node: node19 )
  rel14 = NeoEdge.create(title: "r14", text: "Достать телефон", you_need: "", you_get: "hp-25", from_node: node20, to_node: node11 )
  rel15 = NeoEdge.create(title: "r15", text: "Писать конспект", you_need: "hunger<50, INT>=15", you_get: "hp+25", from_node: node20, to_node: node18 )
  rel16 = NeoEdge.create(title: "r16", text: "Уйти с лекции", you_need: "DEX>=20, STR>=20", you_get: "hp-50", from_node: node20, to_node: node10 )
  rel17 = NeoEdge.create(title: "r17", text: "Не обращать внимания", you_need: "", you_get: "hp-25", from_node: node11, to_node: node12 )
  rel18 = NeoEdge.create(title: "r18", text: "Спрятать телефон", you_need: "DEX>=15, INT>=15", you_get: "hp+1", from_node: node11, to_node: node12 )
  rel19 = NeoEdge.create(title: "r19", text: "Писать лекцию...", you_need: "", you_get: "", from_node: node18, to_node: node13 )
  rel20 = NeoEdge.create(title: "r20", text: "Дожидаться конца лекции", you_need: "", you_get: "", from_node: node12, to_node: node13 )
  rel21 = NeoEdge.create(title: "r21", text: "Купить ДЗ", you_need: "money >=100", you_get: "hp+25", from_node: node19, to_node: node20 )
  rel22 = NeoEdge.create(title: "r22", text: "Сделать ДЗ", you_need: "INT>=15, hunger<50", you_get: "hp+25", from_node: node19, to_node: node20 )
  rel23 = NeoEdge.create(title: "r23", text: "Не делать ничего", you_need: "", you_get: "hp-25", from_node: node19, to_node: node20 )
  rel24 = NeoEdge.create(title: "r24", text: "Another day of doing nothing", you_need: "hp<0", you_get: "", from_node: node13, to_node: node14 )
  rel25 = NeoEdge.create(title: "r25", text: "This is Fine", you_need: "hp>0, hp<50", you_get: "", from_node: node13, to_node: node15 )
  rel26 = NeoEdge.create(title: "r26", text: "fom 0 to 1", you_need: "hp>50", you_get: "", from_node: node13, to_node: node16 )
  rel27 = NeoEdge.create(title: "r27", text: "fom 0 to 1", you_need: "hp>75, hunger>50", you_get: "", from_node: node13, to_node: node17 )

  rel_ug = NeoUG.create(from_node: user, to_node: graph)
  rel_gs = NeoGS.create(from_node: graph, to_node: state)
  rel_first = NeoFirst.create(from_node: graph, to_node: node0)
end
